### ISSUE TITLE
rambler apply --all Requires Old Migration Files to Exist

### ISSUE THREAD

**Issue by emmercm** [elwinar/rambler#32]
**This is kind of special use case, but I have here's a setup I have:**

One repo for programmable infrastructure. This contains migrations that setup up Postgres schemas, users, functions, and so on:

```
$ rambler apply --all
18:31 info  initializing database
18:31 info  found 5 available migrations
18:31 info  found 0 applied migrations
18:31 info  5 migrations to apply
18:31 info  applying 201809070000_uuid-extension.sql
18:31 info  applying 201809070001_public-isolation.sql
18:31 info  applying 201809070002_public-functions.sql
...
18:31 info  done
```

One or more repos for specific services that rely on the programmable infrastructure migrations to have run first. On running their migrations I get:

```
$ rambler apply --all
18:31 info  found 5 available migrations
unable to retrieve applied migrations: unable to open file migrations/201809070000_uuid-extension.sql: open migrations/201809070000_uuid-extension.sql: no such file or directory
```

In my opinion an `apply` doesn't need to read migration files that were already applied, thoughts?

**Comment by emmercm** [comment]
I'm sure this is already known, but running the first set of migrations and then copying them into the second folder yields:

```
$ rambler apply --all
19:43 info  found 10 available migrations
19:43 info  found 5 applied migrations
out of order migration: 20180802-125200_...
```

Though this could be solved by naming the files in the first set before any others.

**Comment by elwinar** [comment]
Although it is not needed sensu stricto, `apply` does in fact read and parse every already available migration, and expect already applied migrations to be available too. This could be changed for something smarter, but your use case isn't the use case that _rambler_ is designed to solve, and I don't want to add any corner-case feature that would result in more complexity than necessary. I'll think about it, this is not a completely trivial change.

As for the second issue, this is actually expected and won't change: migrations must be applied in order and reversed in the inverse order. Adding a migration in the middle of the already existing migrations is semantically an error.

**Comment by emmercm** [comment]
Thank you for considering @elwinar, and thank you for taking the time to write out a thoughtful reply. I've got a workaround that should work for me.

**Comment by FreedomBen** [comment]
For what it's worth, I found this because while working on a team sometimes migrations get merged to master out of order.  I am working around this by requiring all migrations to be idempotent, so it is safe to delete records from the `migrations` table to get rambler to run them again.  Of course this does make the migrations a little tougher to write properly, but I whipped up a quick CI test that makes sure they run multiple times without error and that helps catch missing `IF NOT EXISTS` and other stuff that sometimes happens.

**Comment by emmercm** [comment]
I have a similar use case - one service that is fairly widely innersourced and may have many pull requests open on it at once.

I like the idea of idempotent migrations, though I sometimes do DML migrations that may be tough to make idempotent. That or the migrations have a side effect such as INSERTing into one table will log data in an audit table.

**Comment by elwinar** [comment]
I understand that this could be an issue, but I would be cautious adding this feature given how easy it is to break the migration semantics.

Do you think making your MR with arbitrarily high migration numbers (`999_foo.sql`) then choosing the number at merge-time could be a better solution? Maybe a hook could to this automatically so you don't have to bother?

**Comment by emmercm** [comment]
@elwinar that's what I've started to do in open PRs actually, use a high prefix, but I run into issues on shared staging databases where it's easy to forget to do a "down" before deploying a new branch that doesn't have the applied migrations in it anymore. Such as:

- Deploy open branch A with migration file `999_A.sql`
- Apply migrations
- Forget to run the "down" for `999_A.sql`
- Deploy open branch B with migration file `999_B.sql`
- Apply migrations
- Get the missing file error

It could be solved with a stricter process but it's tough with large projects.

**Comment by elwinar** [comment]
After a little bit of thought (including forgetting this, then remembering it three months later), would a simple `--ignore-missing` flag work? This would probably not be enough, because you would have to do it every time you run the tool, and end-up with a fucked-up migration table.

What about a `tidy` command to look for errors and fix them? With a dry-run displaying what's to be done, you could review that the missing migrations are the correct one then remove them from the table.

I'm not a fan of either solution because it's basically bypassing the checks that ensure you don't fuck-up, and those checks are one of the reasons I built rambler.

Depending on the size of your database, maybe just destroying it and re-running from scratch would be acceptable?

**Comment by emmercm** [comment]
I think a `--ignore-missing` flag should work fine, tools like Flyway have a similar option: https://flywaydb.org/documentation/usage/commandline/migrate.

Not sure I'm understanding the `tidy` command, would that just validate for errors, such as missing files?

Unfortunately destructive actions wouldn't work with a production database.
