### ISSUE TITLE
Support PG schemas

### ISSUE THREAD

**Issue by virmundi** [elwinar/rambler#39]
PG differentiates between schema and database. It also recommends against the use of public to the point that a PG admin will delete the schema 'public'. The present state of the tool does not support schemas. Please enable them.

A PG schema is defined as schema.table. While it is possible that someone might have a table name with '.' in it, they are operating outside the norm of PG. It is also possible to write a SQL statement that FQ's the database name like 'db.schema.table' though it odd and against best-practices.

At minimum the tool needs to support schema.table. The migration table needs to live in the schema, not in public. Failing to properly isolate the migration in the schema can lead to undefined behavior when multiple projects independently run rambler under different schemas.

**Comment by elwinar** [comment]
As we said earlier, I believe that migration themselves will run just fine with a qualified name, although it is burdensome to write it in every file.

The real pain point here is the check for the table existence, as the qualified name won't match the values of the table (here: https://github.com/elwinar/rambler/blob/master/driver/postgresql/driver.go#L44).

A very quick-and-dirty fix would be to modify it to something like `SELECT table_name FROM information_schema.tables WHERE table_catalog = $1 AND table_schema||'.'||table_name = $2` and add something to add the `public` schema to non-qualified configuration. 

It works and solve the issue _stricto sensu_, but I don't feel very right with this, because although PG is the special snowflake here, it isn't very practical to have to add the schema to every table name. We would want to allow specifying the schema in the configuration, and allowing each driver to get it's own configuration as needed.

What I would do is change the driver interface to accept an `Environment` as parameter and let each driver do it's own DSN formatting. This would require pulling `Environment` out of the main package, and adding the relevant parameters to the struct. It would also have the advantage of removing this horrendous `Environment.DSN()` method, and allowing many customization options for each driver, which is good. Also the occasion to cleanup the driver field names, which are a little bit odd at the moment.

I feel we could go one step further by transforming the Environment into a `map[string]interface{}` so we don't have to modify it for every driver and even have drivers with conflicting configurations, but I think it would be unnecessarily complex for our needs.

?

**Comment by elwinar** [comment]
Closed by e45ee57351d60daf813b9197fd6850ed8d2d7a38.
