### ISSUE TITLE
Revert on error

### ISSUE THREAD

**Issue by babariviere** [elwinar/rambler#44]
## Context

For a migration like this:

```sql
-- rambler up
CREATE TABLE ...

-- rambler down
DROP TABLE ...

-- rambler up
-- a failing query here

-- rambler down
-- ...
```

Workflow:
We run rambler apply, the first up works but the second one fails.
We fix the second query, but we can't run it because the first one will fail as the resource is already created.

## Proposal

Revert migration for created resources.

Using the exemple above, if second query fails, `DROP TABLE` must be run.

**Comment by elwinar** [comment]
Hi.

For the example of create table queries, you should probably add the `if exists` clause for now, this avoid the issue with re-running the migration.

Now, the proposal is interesting but there is a few things to sort out before deciding what to do:

You assume that the migrations are always in this order. This is not always true, I've personally used the following migration pattern:

```
-- rambler up
create table ...

-- rambler up
insert into table ...

-- rambler down
drop table
```

In this case, running _down queries_ in reverse order isn't really going to help. I don't really like forcing a strict ordering down the user, especially in this case as the ordering of the queries would change what happens when something goes wrong. What if the _down query_ is failing too? What if the down query is successful but removes important data that was migrated during a first query that succeeded?

**Comment by babariviere** [comment]
I was using it only for demonstration purpose :smile: 

But yes, you are totally right.

For the ordering, I can think of multiple solutions:
1. you can (optionally) assign an order for requests. e.g:
```sql
-- rambler up 1
...
-- rambler up 2
...
-- rambler down 2
...
```
it's ugly but you can set the order.

2. allow user to run down commands

I am aware that's a difficult case to manage, but this feature will really help to develop in SQL faster.

**Comment by elwinar** [comment]
Sorry for the long wait, I've been quite busy until this week. 

I think we can add two features to help you, without forcing anything in the workflow:

1. Allow to run a command without registering it. I don't want it to be something that can be automatic, to avoid ending-up with complex scenarios, but a simple flag would do.
2. Allow executing an arbitrary file with a command. This is fairly limited in impact and is more a side-feature than something that will have an impact on the workflow.

Both of those would allow you to run the down part of the migration that failed to cleanup, without risking fucking things up automatically.

Would this work for you?

**Comment by babariviere** [comment]
I think the first option will be good !

**Comment by elwinar** [comment]
I've got both options implemented in master. Would you care to test it and confirm it solves your issue?

**Comment by babariviere** [comment]
I will try tomorrow, thank you

**Comment by babariviere** [comment]
It's good to me

**Comment by elwinar** [comment]
OK. I'll release it in an official version this evening.
