### ISSUE TITLE
Support for Alpine Linux (docker)

### ISSUE THREAD

**Issue by lydell** [elwinar/rambler#45]
Hi! Thanks for the very nice tool!

I’m trying to add rambler to our existing docker image, which uses alpine:

```Dockerfile
RUN wget -O rambler https://github.com/elwinar/rambler/releases/download/v5.1.0/rambler-linux-amd64
RUN chmod +x rambler
```

However, I get this error when trying to run the downloaded file inside docker:

```Dockerfile
standard_init_linux.go:211: exec user process caused "no such file or directory"
```

Switching to a non-alpine docker image makes rambler work, but I’d like to stay with alpine.

I don’t know much about this stuff, but as far as I understand you would need to provide a musl version of the linux binaries in addition to the glibc ones provided now.

Here’s a sample Dockerfile to try things out:

```Dockerfile
FROM alpine

RUN wget -O rambler https://github.com/elwinar/rambler/releases/download/v5.1.0/rambler-linux-amd64
RUN chmod +x rambler

ENTRYPOINT ["/rambler"]
CMD ["--help"]
```

Would it be possible to add alpine support? Thanks!

**Comment by elwinar** [comment]
Hi.

I currently use github.com/karalabe/xgo for building the releases, and I don't think this support alpine. There was an issue for it to support chosing the libc flavor, but it's open since 2016 and probably won't be done.

I'll see what I can do, but I would like to avoid having to do too much manual work. Not that I release anything regularly. I'll keep you updated.

**Comment by elwinar** [comment]
OK, I built for alpine manually, you can find the binary on the last release https://github.com/elwinar/rambler/releases/tag/v5.1.0. (rambler-alpine-amd64).
I haven't found a satisfying way to have a standard build for alpine, but I will close this issue nonetheless and move on. This isn't too much work to build it by hand once or twice when I do a new release, especially since I plan to avoid feature bloat.

**Comment by lydell** [comment]
Thanks! :100:

**Comment by lydell** [comment]
Hi again!

Did you forget to make an alpine release for 5.2.0?

Luckily, I don’t need the new features in 5.2.0 in docker, but anyway?

Thanks.

**Comment by elwinar** [comment]
:innocent: . It's fixed. I've also comited something quick and dirty so as not forget it next time.

**Comment by lydell** [comment]
Awesome! 🥇
