### ISSUE TITLE
Installation on mac

### ISSUE THREAD

**Issue by shadabb2000** [elwinar/rambler#50]
Hi,

I installed go on mac and executed the installation using 
go install github.com/elwinar/rambler@latest

go: finding module for package github.com/go-sql-driver/mysql
go: finding module for package github.com/client9/xson/hjson
go: finding module for package github.com/mattn/go-sqlite3
go: finding module for package github.com/bradfitz/slice
go: finding module for package github.com/lib/pq
go: finding module for package github.com/kelseyhightower/envconfig
go: finding module for package github.com/urfave/cli
go: finding module for package github.com/imdario/mergo
go: found github.com/bradfitz/slice in github.com/bradfitz/slice v0.0.0-20180809154707-2b758aa73013
go: found github.com/client9/xson/hjson in github.com/client9/xson v0.0.0-20180321172152-0e50cdfc08c0
go: found github.com/imdario/mergo in github.com/imdario/mergo v0.3.12
go: found github.com/kelseyhightower/envconfig in github.com/kelseyhightower/envconfig v1.4.0
go: found github.com/urfave/cli in github.com/urfave/cli v1.22.5
go: found github.com/go-sql-driver/mysql in github.com/go-sql-driver/mysql v1.6.0
go: found github.com/lib/pq in github.com/lib/pq v1.10.3
go: found github.com/mattn/go-sqlite3 in github.com/mattn/go-sqlite3 v1.14.9

I get only this much log and not logs after this and cannot find rambler command in the terminal to execute. Tried a new terminal window as well.
I downloaded rambler-darwin-10.6-amd64 but how do you execute it?
I am new to go just wanted to run some existing migrations. Please help me install rambler.

**Comment by elwinar** [comment]
Hey, sorry for not answering right away, I forgot about it. 

Your issue is probably that you don't have the installation directory in your PATH. I don't use Mac myself, but this SO answer https://stackoverflow.com/questions/28446258/how-does-installers-set-path-variable-on-mac-osx points to a directory `/etc/path.d` which should contain a file named `go`. The first step would be ensuring it is there.

If you downloaded the binary from the release, you should be able to execute it directly in your terminal `./path/to/executable`.
